# Generated by Django 3.2.6 on 2021-08-18 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Логин клиента')),
                ('spent_money', models.FloatField(default=0.0, verbose_name='Всего потрачено средств')),
            ],
            options={
                'verbose_name': ['Клиент'],
                'verbose_name_plural': ['Клиенты'],
                'db_table': 'customers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=300, verbose_name='Наименование товара')),
                ('total', models.FloatField(verbose_name='Сумма сделки')),
                ('quantity', models.IntegerField(verbose_name='Количество товара, шт')),
                ('date', models.DateTimeField(verbose_name='Дата и время регистрации сделки')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='api_service.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': ['Сделка'],
                'verbose_name_plural': ['Сделки'],
                'db_table': 'deals',
                'ordering': ['-date'],
            },
        ),
    ]
