# Generated by Django 3.2.6 on 2021-08-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['-date'], 'verbose_name': 'Сделка', 'verbose_name_plural': 'Сделки'},
        ),
        migrations.AddField(
            model_name='deal',
            name='transaction_number',
            field=models.CharField(default='', max_length=30, verbose_name='Код транзакции, в которой обрабатывался CSV-файл'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deal',
            name='date',
            field=models.DateTimeField(verbose_name='Дата и время сделки'),
        ),
    ]
